#!/usr/bin/env bash
REALNAME=$(pass git/realname)
EMAIL=$(pass git/email)
REPLACE() {
  if [[ ! $REALNAME ]]; then
    pass insert git/realname
  fi
  if [[ ! $EMAIL ]]; then
    pass insert git/email
  fi
  sed -e "s/$1/$2/g" -e "s/$3/$4/g" $5 >$6
}
REPLACE REALNAME "$REALNAME" EMAIL "$EMAIL" config.tmpl config
