#!/usr/bin/env bash
declare -A GITCRED=(
  [REALNAME]=git/realname
  [EMAIL]=git/email
)
REPLACE() {
  for CRED in ${GITCRED[@]}; do
    if ! pass $CRED &>/dev/null; then
      pass insert $CRED
    fi
  done
  sed -e "s/$1/$2/g" -e "s/$3/$4/g" $5 >$6
}
REPLACE REALNAME "$(pass ${GITCRED[REALNAME]})" EMAIL "$(pass ${GITCRED[EMAIL]})" config.tmpl config
